export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_VIDEOS = "FETCH_VIDEOS";
export const SEARCH_VIDEOS = "SEARCH_VIDEOS";
export const CATEGORIZED_VIDEOS = "CATEGORIZED_VIDEOS";
export const CLEAR_SEARCHED = "CLEAR_SEARCHED";
export const LOADING = "LOADING";

export const FETCH_CREATORS = "FETCH_CREATOR";
export const LOAD_CREATORS_BY_CATEGORY = "LOAD_CREATORS_BY_CATEGORY";
export const LOAD_CREATORS_DETAIL = "LOAD_CREATORS_DETAIL";

export const LOAD_DETAIL = "LOAD_DETAIL";
export const LOADING_DETAIL = "LOADING_DETAIL";
